version: '3.3'

services:
  database:
    image:
      postgres
    container_name:
      postgres_database
    ports:
      - "8081:5432"
    networks:
      - tracker_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    volumes:
      - tracker_postgres_volume:/var/lib/postgresql/data

volumes:
  tracker_postgres_volume:
    external: true

networks:
  tracker_network:
    external: true
